# Generated by Django 5.0 on 2023-12-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Активен')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.student', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('dedlaine', models.DateField(null=True, verbose_name='Дата доставки')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто заказал')),
                ('projects', models.ManyToManyField(related_name='tasks', to='core.project', verbose_name='Заказы')),
                ('students', models.ManyToManyField(related_name='tasks', to='core.student', verbose_name='Клиенты')),
            ],
        ),
    ]
